/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'diegoferreira' at '5/16/16 8:23 AM' with Gradle 2.12
 *
 * @author diegoferreira, @date 5/16/16 8:23 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
